Repository vc1492a/PyNomaly, pull requests merged in 2024-10, with the labels that each got.

#63 49 passing cluster labels broken
  .travis.yml
  MANIFEST
  PyNomaly/loop.py
  readme.md
  setup.cfg
  setup.py
  tests/test_loop.py
Labels: bug, review

#65 Merge dev to main branch
  .github/workflows/release-please.yml
  .travis.yml
  MANIFEST
  PyNomaly/loop.py
  readme.md
  setup.cfg
  setup.py
  tests/test_loop.py
Labels: bug

#68 67 display readme properly on pypi
  LICENSE
  setup.py
Labels: documentation
